### ISSUE TITLE
Volumetric Clouds appear 2D on surface of Kerbin and don't appear when on the ground

### ISSUE THREAD

**Issue by su25jsk** [jthero3/JNSQVolumetrics#5]
<img width="755" height="760" alt="Image" src="https://github.com/user-attachments/assets/d7bb8990-2913-494b-9a39-ffbde645518b" />

<img width="1729" height="737" alt="Image" src="https://github.com/user-attachments/assets/df1b6abb-3480-4cc8-bbde-64fff25d2577" />

https://mclo.gs/DehkRdm

**Comment by ghost** [comment]
the ground issue seems to have been fixed but it still looks strange from orbit

**Comment by StrandedSurvivor** [comment]
Same issue for me. Reverting to 3.1.1 fixes the issue for me. You still get all the cloud improvements, just none of the new patterns.
